version: '3'
services:
    web:
        build: .
        volumes:
            - ./:/usr/src/app
        ports:
            - '5000:5000'
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        volumes:
            - ./dump/naoled:/data/db/naoled
        ports:
            - '27017:27017'
